use clido_planner::Plan;

// ── Agent → TUI events ────────────────────────────────────────────────────────

#[allow(dead_code)]
pub(crate) enum AgentEvent {
    ToolStart {
        tool_use_id: String,
        name: String,
        detail: String,
    },
    ToolDone {
        tool_use_id: String,
        is_error: bool,
        diff: Option<String>,
    },
    /// Intermediate text the model emits while it's still calling tools.
    Thinking(String),
    Response(String),
    Interrupted,
    Err(String),
    /// Provider rate limit — carries structured info for special TUI handling.
    RateLimited {
        message: String,
        retry_after_secs: Option<u64>,
        is_subscription_limit: bool,
    },
    /// Emitted once when the agent session is created.
    SessionStarted(String),
    /// Emitted when a session is resumed; carries display messages.
    ResumedSession {
        messages: Vec<(String, String)>,
    },
    /// Token usage update after agent turn completion.
    TokenUsage {
        input_tokens: u64,
        output_tokens: u64,
        cost_usd: f64,
        context_max_tokens: u64,
    },
    /// Emitted once by the `/compact` command after history is compacted.
    Compacted {
        before: usize,
        after: usize,
    },
    /// Emitted when the planner produces a valid task graph (--planner mode).
    /// Each string is a human-readable description of one planned task.
    PlanCreated {
        tasks: Vec<String>,
    },
    /// Emitted when the session model is switched (via /model, /fast, /smart).
    ModelSwitched {
        to_model: String,
    },
    /// Emitted when background runtime successfully switches workdir/tooling.
    WorkdirSwitched {
        path: std::path::PathBuf,
    },
    /// Plan generated and ready for user review (--plan mode).
    PlanReady {
        plan: Plan,
    },
    /// A plan task started executing.
    #[allow(dead_code)]
    PlanTaskStarted {
        task_id: String,
    },
    /// A plan task completed.
    #[allow(dead_code)]
    PlanTaskDone {
        task_id: String,
        success: bool,
    },
    /// Periodic keep-alive from agent_task while waiting on a slow LLM response.
    /// Resets the stall timer without producing any visible output.
    Heartbeat,
    /// Emitted when cumulative cost crosses a budget threshold (50%, 80%, or 90%).
    BudgetWarning {
        percent: u8,
        cost: f64,
        limit: f64,
    },
    /// Emitted when models are fetched live from the provider API.
    ModelsLoaded {
        ids: Vec<String>,
        provider: String,
    },
    /// Emitted when a model fetch fails (e.g. invalid API key, network error).
    ModelsFetchFailed {
        provider: String,
        error: String,
    },
    /// Emitted when a session title is generated by the fast model.
    TitleGenerated(String),
    /// Emitted when `/enhance` completes — carries the enhanced prompt to submit.
    EnhancedPrompt(String),
    /// Emitted by the background update check when a newer release is available.
    UpdateAvailable {
        version: String,
    },
    /// Progress/result message from the `/update` command's async install task.
    UpdateStatus(String),
    /// General info message to display in the chat (non-error, non-response).
    Info {
        message: String,
    },
    /// Agent loop phase for status rail / input dock (model vs tools).
    RunState(crate::tui::app_state::AppRunState),
    /// Request permission to access a path outside the workspace.
    /// The TUI should prompt the user and respond via the permission channel.
    #[allow(dead_code)]
    PathPermissionRequest {
        path: std::path::PathBuf,
        tool_name: String,
    },
    /// A workflow step started executing.
    WorkflowStepStarted {
        step_id: String,
        name: String,
        step_num: usize,
        total: usize,
    },
    /// A workflow step completed (output_text is the full step output).
    WorkflowStepDone {
        step_id: String,
        name: String,
        output_text: String,
        cost_usd: f64,
        duration_ms: u64,
    },
    /// A workflow step failed. `fatal` = true means the whole workflow stops.
    WorkflowStepFailed {
        step_id: String,
        name: String,
        error: String,
        fatal: bool,
    },
    /// All workflow steps finished successfully.
    WorkflowComplete {
        name: String,
        step_count: usize,
        total_cost_usd: f64,
        total_duration_ms: u64,
    },
    /// Workflow aborted due to a fatal step failure.
    WorkflowFailed {
        name: String,
        step_id: String,
        error: String,
    },
    /// Results from a parallel step batch — all isolated agents finished.
    WorkflowParallelBatchDone {
        /// (step_id, output_text, cost_usd, duration_ms)
        outputs: Vec<(String, String, f64, u64)>,
    },
}
