use clido_planner::Plan;

// ── Agent → TUI events ────────────────────────────────────────────────────────

pub(super) enum AgentEvent {
    ToolStart {
        tool_use_id: String,
        name: String,
        detail: String,
    },
    ToolDone {
        tool_use_id: String,
        is_error: bool,
        diff: Option<String>,
    },
    /// Intermediate text the model emits while it's still calling tools.
    Thinking(String),
    Response(String),
    Interrupted,
    Err(String),
    /// Provider rate limit — carries structured info for special TUI handling.
    RateLimited {
        message: String,
        retry_after_secs: Option<u64>,
        is_subscription_limit: bool,
    },
    /// Emitted once when the agent session is created.
    SessionStarted(String),
    /// Emitted when a session is resumed; carries display messages.
    ResumedSession {
        messages: Vec<(String, String)>,
    },
    /// Token usage update after agent turn completion.
    TokenUsage {
        input_tokens: u64,
        output_tokens: u64,
        cost_usd: f64,
        context_max_tokens: u64,
    },
    /// Emitted once by the `/compact` command after history is compacted.
    Compacted {
        before: usize,
        after: usize,
    },
    /// Emitted when the planner produces a valid task graph (--planner mode).
    /// Each string is a human-readable description of one planned task.
    PlanCreated {
        tasks: Vec<String>,
    },
    /// Emitted when the session model is switched (via /model, /fast, /smart).
    ModelSwitched {
        to_model: String,
    },
    /// Emitted when background runtime successfully switches workdir/tooling.
    WorkdirSwitched {
        path: std::path::PathBuf,
    },
    /// Plan generated and ready for user review (--plan mode).
    PlanReady {
        plan: Plan,
    },
    /// A plan task started executing.
    #[allow(dead_code)]
    PlanTaskStarted {
        task_id: String,
    },
    /// A plan task completed.
    #[allow(dead_code)]
    PlanTaskDone {
        task_id: String,
        success: bool,
    },
    /// Periodic keep-alive from agent_task while waiting on a slow LLM response.
    /// Resets the stall timer without producing any visible output.
    Heartbeat,
    /// Emitted when cumulative cost crosses a budget threshold (50%, 80%, or 90%).
    BudgetWarning {
        percent: u8,
        cost: f64,
        limit: f64,
    },
    /// Emitted when models are fetched live from the provider API.
    ModelsLoaded(Vec<String>),
    /// Emitted when a session title is generated by the fast model.
    TitleGenerated(String),
    /// Emitted when `/enhance` completes — carries the enhanced prompt to submit.
    EnhancedPrompt(String),
}
